name: Release

permissions:
  contents: write

on:
  push:
    branches:
      - main
    paths:
      - '*.py'
      - 'blender_manifest.toml'
      - 'version.txt'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Zip file
        run: make build

      - name: Create or update release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          release_name: "Latest Release"
          draft: false
          prerelease: false
          files: ./*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
